package com.floweytf.customitemapi.datadriven.registry;

import com.floweytf.customitemapi.datadriven.Utils;
import net.kyori.adventure.text.Component;

public enum MonumentaLocations {
    LABS("Alchemy Labs", "#B4ACC3"),
    WHITE("Halls of Wind and Blood", "white"),
    ORANGE("Fallen Menagerie", "gold"),
    MAGENTA("Plagueroot Temple", "light_purple"),
    LIGHTBLUE("Arcane Rivalry", "#4AC2E5"),
    YELLOW("Vernal Nightmare", "yellow"),
    LIME("Salazar's Folly", "green"),
    PINK("Harmonic Arboretum", "#FF69B4"),
    GRAY("Valley of Forgotten Pharaohs", "dark_gray"),
    LIGHTGRAY("Palace of Mirrors", "gray"),
    CYAN("The Scourge of Lunacy", "dark_aqua"),
    PURPLE("The Grasp of Avarice", "dark_purple"),
    TEAL("Echoes of Oblivion", "#47B6B5"),
    BLUE("Coven's Gambit", "#0C2CA2"),
    BROWN("Cradle of the Broken God", "#703608"),
    INDIGO("Indigo Dungeon", "white"),
    GREEN("Green Dungeon", "white"),
    RED("Red Dungeon", "white"),
    BLACK("Black Dungeon", "white"),
    VERDANT("Verdant Remnants", "#158315"),
    SANCTUM("Forsworn Sanctum", "#52AA00"),
    MIST("The Black Mist", "#674C5B"),
    REMORSE("Sealed Remorse", "#EEE6D6"),
    VIGIL("The Eternal Vigil", "#72999C"),
    BLUESTRIKE("Masquerader's Ruin", "#326DA8"),
    SCIENCE("P.O.R.T.A.L.", "#DCE8E3"),
    REVERIE("Malevolent Reverie", "#790E47"),
    FORUM("The Fallen Forum", "#808000"),
    SILVER("Silver Knight's Tomb", "#C0C0C0"),
    HOARD("The Hoard", "#DAAD3E"),
    EPHEMERAL("Ephemeral Corridors", "#8B0000"),
    EPHEMERALENHANCEMENTS("Ephemeral Enhancements", "#8B0000"),
    WILLOWS("The Black Willows", "#006400"),
    RUSH("Rush of Dissonance", "#C21E56"),
    SHIFTING("City of Shifting Waters", "#7FFFD4"),
    DEPTHS("Darkest Depths", "#5D2D87"),
    GALLERYBASE("Gallery of Fear", "#39B14E"),
    GALLERY1("Sanguine Halls", "#AB0000"),
    GALLERY2("Marina Noir", "#324150"),
    ZENITH("The Celestial Zenith", "#FF9CF0"),
    OVERWORLD1("King's Valley Overworld", "#DCAE32"),
    OVERWORLD2("Celsian Isles Overworld", "#32D7DC"),
    FOREST("The Wolfswood", "#4C8F4D"),
    KEEP("Pelias' Keep", "#C4BBA5"),
    STARPOINT("Star Point", "#342768"),
    FISHING("Architect's Ring Fishing", "#A9D1D0"),
    OVERWORLD3("Architect's Ring Overworld", "#C2C4C4"),
    QUEST("Quest Reward", "#C8A2C8"),
    KAUL("Kaul's Judgment", "dark_green"),
    AZACOR("Azacor's Malice", "#FF6F55"),
    SIRIUS("The Final Blight", "#34CFBC"),
    GODSPORE("The Godspore's Domain", "#426B29"),
    FROSTGIANT("The Waking Giant", "#87CEFA"),
    LICH("Hekawt's Fury", "#FFB43E"),
    CASINO1("Rock's Little Casino", "#EDC863"),
    CASINO2("Monarch's Cozy Casino", "#1773B1"),
    CASINO3("Sticks and Stones Tavern", "#C6C2B6"),
    APRILFOOLS("April Fools Event", "#D22AD2"),
    EASTER("Easter Event", "green"),
    UGANDA("Uganda 2018", "#D02E28"),
    HALLOWEEN("Halloween Event", "gold"),
    VALENTINE("Valentine Event", "#FF7F7F"),
    WINTER("Winter Event", "#AFC2E3"),
    TREASURE("Treasures of Viridia", "#C8A2C8"),
    TRICKSTER("Trickster Challenge", "gold"),
    HORSEMAN("The Headless Horseman", "#8E3418"),
    SEASONPASS("Seasonal Pass", "#FFF63C"),
    LIGHT("Arena of Terth", "#FFFFAA"),
    HOLIDAYSKIN("Holiday Skin", "#B00C2F"),
    SKETCHED("Sketched Skin", "#FFF63C"),
    CHALLENGER("Challenger Skin", "#FEDC10"),
    DIVINE("Divine Skin", "#C6EFF1"),
    VERDANTSKIN("Threadwarped Skin", "#704C8A"),
    HALLOWEENSKIN("Halloween Skin", "gold"),
    WILLOWSKIN("Storied Skin", "#006400"),
    TITANICSKIN("Titanic Skin", "#87CEFA"),
    ETERNITYSKIN("Eternity Skin", "#FFB43E"),
    REMORSEFULSKIN("Remorseful Skin", "#EEE6D6"),
    GREEDSKIN("Greed Skin", "#DAAD3E"),
    MYTHIC("Mythic Reliquary", "#C4971A"),
    LOWTIDE("Lowtide Smuggler", "#196383"),
    ROYAL("Royal Armory", "#CAFFFD"),
    TRANSMOGRIFIER("Transmogrifier", "#6F2DA8"),
    SOUL("Soulwoven", "#7FFFD4"),
    TRUENORTH("True North", "#FFD700"),
    DOCKS("Expedition Docks", "#196383"),
    CARNIVAL("Floating Carnival", "#D02E28"),
    INTELLECT("Intellect Crystallizer", "#82DB17"),
    DELVES("Dungeon Delves", "#B47028"),
    BLITZ("Plunderer's Blitz", "#DAAD3E"),
    ;
    private final Component text;

    MonumentaLocations(String text, String color) {
        this.text = Component.text(text).color(Utils.colorFromString(color));
    }

    public Component getText() {
        return text;
    }
}