package com.floweytf.customitemapi.datadriven.registry;

import com.google.gson.JsonElement;

public enum MonumentaCharmAttributes {
    ALCHEMICAL_ARTILLERY_DAMAGE("Alchemical Artillery Damage", false),
    ALCHEMICAL_ARTILLERY_VELOCITY("Alchemical Artillery Velocity", false),
    BEZOAR_DAMAGE_DURATION("Bezoar Damage Duration", false),
    BEZOAR_DAMAGE_MODIFIER("Bezoar Damage Modifier", false),
    TRANSMUTATION_RING_DAMAGE_AMPLIFIER("Transmutation Ring Damage Amplifier", false),
    TRANSMUTATION_RING_PER_DEATH_AMPLIFIER("Transmutation Ring Per Death Amplifier", false),
    ALCHEMICAL_ARTILLERY_RADIUS("Alchemical Artillery Radius", false),
    TRANSMUTATION_RING_RADIUS("Transmutation Ring Radius", false),
    TRANSMUTATION_RING_DURATION("Transmutation Ring Duration", false),
    ESOTERIC_ENHANCEMENTS_DAMAGE("Esoteric Enhancements Damage", false),
    ESOTERIC_ENHANCEMENTS_RADIUS("Esoteric Enhancements Radius", false),
    ESOTERIC_ENHANCEMENTS_BLEED_AMPLIFIER("Esoteric Enhancements Bleed Amplifier", false),
    SCORCHED_EARTH_DAMAGE("Scorched Earth Damage", false),
    SCORCHED_EARTH_RADIUS("Scorched Earth Radius", false),
    SCORCHED_EARTH_DURATION("Scorched Earth Duration", false),
    UNSTABLE_AMALGAM_DAMAGE("Unstable Amalgam Damage", false),
    UNSTABLE_AMALGAM_RADIUS("Unstable Amalgam Radius", false),
    WARDING_REMEDY_RADIUS("Warding Remedy Radius", false),
    WARDING_REMEDY_COOLDOWN("Warding Remedy Cooldown", true),
    BRUTAL_ALCHEMY_DOT_DAMAGE("Brutal Alchemy DoT Damage", false),
    ALCHEMIST_POTION_DAMAGE("Alchemist Potion Damage", false),
    UNSTABLE_AMALGAM_KNOCKBACK_SPEED("Unstable Amalgam Knockback Speed", false),
    ENERGIZING_ELIXIR_DAMAGE_MODIFIER("Energizing Elixir Damage Modifier", false),
    ENERGIZING_ELIXIR_SPEED_MODIFIER("Energizing Elixir Speed Modifier", false),
    ENERGIZING_ELIXIR_EFFECT_DURATION("Energizing Elixir Effect Duration", false),
    TABOO_DAMAGE_MODIFIER("Taboo Damage Modifier", false),
    TABOO_KNOCKBACK_RESISTANCE("Taboo Knockback Resistance", false),
    GRUESOME_ALCHEMY_DAMAGE_MULTIPLIER("Gruesome Alchemy Damage Multiplier", false),
    GRUESOME_ALCHEMY_SLOWNESS_AMPLIFIER("Gruesome Alchemy Slowness Amplifier", false),
    GRUESOME_ALCHEMY_VULNERABILITY_AMPLIFIER("Gruesome Alchemy Vulnerability Amplifier", false),
    PANACEA_ABSORPTION_HEALTH("Panacea Absorption Health", false),
    PANACEA_DAMAGE("Panacea Damage", false),
    PANACEA_DOT_DAMAGE("Panacea DoT Damage", false),
    IRON_TINCTURE_ABSORPTION_HEALTH("Iron Tincture Absorption Health", false),
    EMPOWERING_ODOR_SPEED_MODIFIER("Empowering Odor Speed Modifier", false),
    EMPOWERING_ODOR_DAMAGE_BONUS("Empowering Odor Damage Bonus", false),
    WARDING_REMEDY_PULSE_DELAY("Warding Remedy Pulse Delay", true),
    WARDING_REMEDY_MAX_ABSORPTION_HEALTH("Warding Remedy Max Absorption Health", false),
    BEZOAR_GENERATION_REQUIREMENT("Bezoar Generation Requirement", true),
    BEZOAR_LINGER_DURATION("Bezoar Linger Duration", false),
    TRANSMUTATION_RING_COOLDOWN("Transmutation Ring Cooldown", true),
    BEZOAR_DEBUFF_REDUCTION("Bezoar Debuff Reduction", false),
    ENERGIZING_ELIXIR_JUMP_BOOST_MODIFIER("Energizing Elixir Jump Boost Modifier", false),
    PANACEA_RADIUS("Panacea Radius", false),
    PANACEA_SLOW_DURATION("Panacea Slow Duration", false),
    UNSTABLE_AMALGAM_CAST_RANGE("Unstable Amalgam Cast Range", false),
    BEZOAR_HEALING_DURATION("Bezoar Healing Duration", false),
    TABOO_HEALING_PENALTY("Taboo Healing Penalty", true),
    TABOO_ABSORPTION_PENALTY("Taboo Absorption Penalty", true),
    WARDING_REMEDY_HEALING_BONUS("Warding Remedy Healing Bonus", false),
    TRASMUTATION_RING_DAMAGE_AMPLIFIER("Trasmutation Ring Damage Amplifier", false),
    TRASMUTATION_RING_COOLDOWN("Trasmutation Ring Cooldown", true),
    ESOTERIC_ENHANCEMENTS_COOLDOWN("Esoteric Enhancements Cooldown", true),
    SCORCHED_EARTH_COOLDOWN("Scorched Earth Cooldown", true),
    PANACEA_COOLDOWN("Panacea Cooldown", true),
    UNSTABLE_AMALGAM_COOLDOWN("Unstable Amalgam Cooldown", true),
    IRON_TINCTURE_COOLDOWN("Iron Tincture Cooldown", true),
    IRON_TINCTURE_VELOCITY("Iron Tincture Velocity", false),
    ALCHEMIST_POTION_CHARGES("Alchemist Potion Charges", false),
    CELESTIAL_BLESSING_RADIUS("Celestial Blessing Radius", false),
    CELESTIAL_BLESSING_DURATION("Celestial Blessing Duration", false),
    CLEANSING_RAIN_DAMAGE_REDUCTION("Cleansing Rain Damage Reduction", false),
    CLEANSING_RAIN_RANGE("Cleansing Rain Range", false),
    HAND_OF_LIGHT_DAMAGE("Hand of Light Damage", false),
    HAND_OF_LIGHT_HEALING("Hand of Light Healing", false),
    HAND_OF_LIGHT_RANGE("Hand of Light Range", false),
    HOLY_JAVELIN_DAMAGE("Holy Javelin Damage", false),
    HOLY_JAVELIN_RANGE("Holy Javelin Range", false),
    HALLOWED_BEAM_DAMAGE("Hallowed Beam Damage", false),
    HALLOWED_BEAM_DISTANCE("Hallowed Beam Distance", false),
    ILLUMINATE_DAMAGE("Illuminate Damage", false),
    ILLUMINATE_TRAIL_WIDTH("Illuminate Trail Width", false),
    ILLUMINATE_MAX_RANGE("Illuminate Max Range", false),
    CHOIR_BELLS_DAMAGE("Choir Bells Damage", false),
    CHOIR_BELLS_RANGE("Choir Bells Range", false),
    LUMINOUS_INFUSION_DAMAGE("Luminous Infusion Damage", false),
    LUMINOUS_INFUSION_RADIUS("Luminous Infusion Radius", false),
    ENCHANTED_PRAYER_DAMAGE("Enchanted Prayer Damage", false),
    ENCHANTED_PRAYER_HEALING("Enchanted Prayer Healing", false),
    ENCHANTED_PRAYER_RANGE("Enchanted Prayer Range", false),
    ENCHANTED_PRAYER_ATTACK_RANGE("Enchanted Prayer Attack Range", false),
    HEAVENLY_BOON_POTION_CHANCE("Heavenly Boon Potion Chance", false),
    HEAVENLY_BOON_POTION_DURATION("Heavenly Boon Potion Duration", false),
    SACRED_PROVISIONS_CHANCE("Sacred Provisions Chance", false),
    SACRED_PROVISIONS_RANGE("Sacred Provisions Range", false),
    SANCTIFIED_ARMOR_DAMAGE("Sanctified Armor Damage", false),
    HALLOWED_BEAM_HEALING("Hallowed Beam Healing", false),
    DIVINE_JUSTICE_DAMAGE("Divine Justice Damage", false),
    ILLUMINATE_VELOCITY("Illuminate Velocity", false),
    CELESTIAL_BLESSING_DAMAGE_MODIFIER("Celestial Blessing Damage Modifier", false),
    CLEANSING_RAIN_DURATION("Cleansing Rain Duration", false),
    CHOIR_BELLS_COOLDOWN("Choir Bells Cooldown", true),
    THURIBLE_PROCESSION_DAMAGE_AMPLIFIER("Thurible Procession Damage Amplifier", false),
    CHOIR_BELLS_SLOWNESS_AMPLIFIER("Choir Bells Slowness Amplifier", false),
    CHOIR_BELLS_VULNERABILITY_AMPLIFIER("Choir Bells Vulnerability Amplifier", false),
    SANCTIFIED_ARMOR_SLOWNESS_AMPLIFIER("Sanctified Armor Slowness Amplifier", false),
    HALLOWED_BEAM_STUN_DURATION("Hallowed Beam Stun Duration", false),
    HALLOWED_BEAM_COOLDOWN("Hallowed Beam Cooldown", true),
    ILLUMINATE_SPEED_AMPLIFIER("Illuminate Speed Amplifier", false),
    ILLUMINATE_TRAIL_DURATION("Illuminate Trail Duration", false),
    DIVINE_JUSTICE_SELF_HEAL("Divine Justice Self Heal", false),
    DIVINE_JUSTICE_ALLY_HEAL("Divine Justice Ally Heal", false),
    CELESTIAL_BLESSING_COOLDOWN("Celestial Blessing Cooldown", true),
    CELESTIAL_BLESSING_SPEED_AMPLIFIER("Celestial Blessing Speed Amplifier", false),
    CLEANSING_RAIN_COOLDOWN("Cleansing Rain Cooldown", true),
    HAND_OF_LIGHT_COOLDOWN("Hand of Light Cooldown", true),
    LUMINOUS_INFUSION_COOLDOWN("Luminous Infusion Cooldown", true),
    HOLY_JAVELIN_COOLDOWN("Holy Javelin Cooldown", true),
    ENCHANTED_PRAYER_COOLDOWN("Enchanted Prayer Cooldown", true),
    ARCANE_STRIKE_DAMAGE("Arcane Strike Damage", false),
    ARCANE_STRIKE_RADIUS("Arcane Strike Radius", false),
    MANA_LANCE_DAMAGE("Mana Lance Damage", false),
    MANA_LANCE_RANGE("Mana Lance Range", false),
    THUNDER_STEP_DAMAGE("Thunder Step Damage", false),
    THUNDER_STEP_DISTANCE("Thunder Step Distance", false),
    STARFALL_DAMAGE("Starfall Damage", false),
    STARFALL_RANGE("Starfall Range", false),
    STARFALL_FIRE_DURATION("Starfall Fire Duration", false),
    FROST_NOVA_DAMAGE("Frost Nova Damage", false),
    FROST_NOVA_COOLDOWN("Frost Nova Cooldown", true),
    FROST_NOVA_RANGE("Frost Nova Range", false),
    MAGMA_SHIELD_DAMAGE("Magma Shield Damage", false),
    MAGMA_SHIELD_COOLDOWN("Magma Shield Cooldown", true),
    MAGMA_SHIELD_RANGE("Magma Shield Range", false),
    ASTRAL_OMEN_DAMAGE("Astral Omen Damage", false),
    ASTRAL_OMEN_DAMAGE_MODIFIER("Astral Omen Damage Modifier", false),
    ARCANE_STRIKE_COOLDOWN("Arcane Strike Cooldown", true),
    BLIZZARD_RANGE("Blizzard Range", false),
    BLIZZARD_COOLDOWN("Blizzard Cooldown", true),
    ELEMENTAL_ARROWS_RANGE("Elemental Arrows Range", false),
    COSMIC_MOONBLADE_DAMAGE("Cosmic Moonblade Damage", false),
    COSMIC_MOONBLADE_RANGE("Cosmic Moonblade Range", false),
    ELEMENTAL_SPIRITS_DAMAGE("Elemental Spirits Damage", false),
    ELEMENTAL_SPIRITS_SIZE("Elemental Spirits Size", false),
    ARCANE_STRIKE_BONUS_DAMAGE("Arcane Strike Bonus Damage", false),
    SPELLSHOCK_SPELL_AMPLIFIER("Spellshock Spell Amplifier", false),
    SPELLSHOCK_MELEE_AMPLIFIER("Spellshock Melee Amplifier", false),
    SPELLSHOCK_SPEED_AMPLIFIER("Spellshock Speed Amplifier", false),
    SPELLSHOCK_SLOWNESS_AMPLIFIER("Spellshock Slowness Amplifier", false),
    BLIZZARD_DAMAGE("Blizzard Damage", false),
    SAGES_INSIGHT_STACK_TRIGGER_THRESHOLD("Sage's Insight Stack Trigger Threshold", true),
    THUNDER_STEP_RADIUS("Thunder Step Radius", false),
    ELEMENTAL_ARROWS_DAMAGE("Elemental Arrows Damage", false),
    PRISMATIC_SHIELD_ABSORPTION_HEALTH("Prismatic Shield Absorption Health", false),
    PRISMATIC_SHIELD_COOLDOWN("Prismatic Shield Cooldown", true),
    PRISMATIC_SHIELD_KNOCKBACK("Prismatic Shield Knockback", false),
    PRISMATIC_SHIELD_STUN_DURATION("Prismatic Shield Stun Duration", false),
    SAGES_INSIGHT_DECAY_DURATION("Sage's Insight Decay Duration", false),
    ELEMENTAL_ARROWS_DURATION("Elemental Arrows Duration", false),
    THUNDER_STEP_COOLDOWN("Thunder Step Cooldown", true),
    BLIZZARD_SLOWNESS_AMPLIFIER("Blizzard Slowness Amplifier", false),
    FROST_NOVA_SLOWNESS_AMPLIFIER("Frost Nova Slowness Amplifier", false),
    FROST_NOVA_SLOWNESS_DURATION("Frost Nova Slowness Duration", false),
    MAGMA_SHIELD_FIRE_DURATION("Magma Shield Fire Duration", false),
    MAGMA_SHIELD_KNOCKBACK("Magma Shield Knockback", false),
    MANA_LANCE_COOLDOWN("Mana Lance Cooldown", true),
    STARFALL_COOLDOWN("Starfall Cooldown", true),
    COSMIC_MOONBLADE_COOLDOWN_REDUCTION("Cosmic Moonblade Cooldown Reduction", false),
    COSMIC_MOONBLADE_COOLDOWN_CAP("Cosmic Moonblade Cooldown Cap", false),
    COSMIC_MOONBLADE_COOLDOWN("Cosmic Moonblade Cooldown", true),
    ELEMENTAL_SPIRITS_COOLDOWN("Elemental Spirits Cooldown", true),
    CLOAK_AND_DAGGER_DAMAGE("Cloak and Dagger Damage", false),
    CLOAK_AND_DAGGER_MAX_STACKS("Cloak and Dagger Max Stacks", false),
    BY_MY_BLADE_DAMAGE("By My Blade Damage", false),
    DAGGER_THROW_DAMAGE("Dagger Throw Damage", false),
    DAGGER_THROW_COOLDOWN("Dagger Throw Cooldown", true),
    DAGGER_THROW_RANGE("Dagger Throw Range", false),
    BODKIN_BLITZ_DAMAGE("Bodkin Blitz Damage", false),
    BODKIN_BLITZ_DISTANCE("Bodkin Blitz Distance", false),
    ESCAPE_DEATH_JUMP_BOOST_AMPLIFIER("Escape Death Jump Boost Amplifier", false),
    ESCAPE_DEATH_SPEED_AMPLIFIER("Escape Death Speed Amplifier", false),
    BLADE_DANCE_DAMAGE("Blade Dance Damage", false),
    BLADE_DANCE_RADIUS("Blade Dance Radius", false),
    ADVANCING_SHADOWS_DAMAGE_MULTIPLIER("Advancing Shadows Damage Multiplier", false),
    ADVANCING_SHADOWS_RANGE("Advancing Shadows Range", false),
    ADVANCING_SHADOWS_KNOCKBACK("Advancing Shadows Knockback", false),
    DEADLY_RONDE_DAMAGE("Deadly Ronde Damage", false),
    COUP_DE_GRACE_THRESHOLD("Coup de Grace Threshold", false),
    SKIRMISHER_DAMAGE_MULTIPLIER("Skirmisher Damage Multiplier", false),
    SKIRMISHER_DAMAGE_RADIUS("Skirmisher Damage Radius", false),
    BODKIN_BLITZ_STEALTH_DURATION("Bodkin Blitz Stealth Duration", false),
    ESCAPE_DEATH_ABSORPTION_HEALTH("Escape Death Absorption Health", false),
    ESCAPE_DEATH_COOLDOWN("Escape Death Cooldown", true),
    DODGING_COOLDOWN("Dodging Cooldown", true),
    DODGING_SPEED_AMPLIFIER("Dodging Speed Amplifier", false),
    VICIOUS_COMBOS_COOLDOWN_REDUCTION("Vicious Combos Cooldown Reduction", false),
    WIND_WALK_COOLDOWN("Wind Walk Cooldown", true),
    SMOKESCREEN_COOLDOWN("Smokescreen Cooldown", true),
    DAGGER_THROW_VULNERABILITY_AMPLIFIER("Dagger Throw Vulnerability Amplifier", false),
    SMOKESCREEN_SLOWNESS_AMPLIFIER("Smokescreen Slowness Amplifier", false),
    BLADE_DANCE_ROOT_DURATION("Blade Dance Root Duration", false),
    BY_MY_BLADE_COOLDOWN("By My Blade Cooldown", true),
    BODKIN_BLITZ_COOLDOWN("Bodkin Blitz Cooldown", true),
    SMOKE_SCREEN_COOLDOWN("Smoke Screen Cooldown", true),
    BLADE_DANCE_COOLDOWN("Blade Dance Cooldown", true),
    ADVANCING_SHADOWS_COOLDOWN("Advancing Shadows Cooldown", true),
    WHIRLING_BLADE_DAMAGE("Whirling Blade Damage", false),
    WHIRLING_BLADE_RADIUS("Whirling Blade Radius", false),
    EAGLE_EYE_RADIUS("Eagle Eye Radius", false),
    EAGLE_EYE_VULNERABILITY_AMPLIFIER("Eagle Eye Vulnerability Amplifier", false),
    WIND_BOMB_HEIGHT("Wind Bomb Height", false),
    WIND_BOMB_RADIUS("Wind Bomb Radius", false),
    PREDATOR_STRIKE_DAMAGE("Predator Strike Damage", false),
    PREDATOR_STRIKE_RADIUS("Predator Strike Radius", false),
    TACTICAL_MANEUVER_DAMAGE("Tactical Maneuver Damage", false),
    TACTICAL_MANEUVER_RADIUS("Tactical Maneuver Radius", false),
    VOLLEY_DAMAGE("Volley Damage", false),
    VOLLEY_ARROWS("Volley Arrows", false),
    PINNING_SHOT_MAX_HEALTH_DAMAGE("Pinning Shot Max Health Damage", false),
    HUNTING_COMPANION_DAMAGE("Hunting Companion Damage", false),
    SHARPSHOOTER_STACK_DAMAGE("Sharpshooter Stack Damage", false),
    SHARPSHOOTER_MAX_STACKS("Sharpshooter Max Stacks", false),
    QUICKDRAW_DAMAGE("Quickdraw Damage", false),
    SPLIT_ARROW_DAMAGE("Split Arrow Damage", false),
    TACTICAL_MANEUVER_VELOCITY("Tactical Maneuver Velocity", false),
    SWIFT_CUTS_STACK_DAMAGE("Swift Cuts Stack Damage", false),
    SWIFTNESS_JUMP_BOOST_AMPLIFIER("Swiftness Jump Boost Amplifier", false),
    WIND_BOMB_DAMAGE("Wind Bomb Damage", false),
    EAGLE_EYE_REFRESH("Eagle Eye Refresh", false),
    SWIFTNESS_SPEED_AMPLIFIER("Swiftness Speed Amplifier", false),
    HUNTING_COMPANION_SPEED("Hunting Companion Speed", false),
    PINNING_SHOT_WEAKNESS_AMPLIFIER("Pinning Shot Weakness Amplifier", false),
    WIND_BOMB_WEAKEN_AMPLIFIER("Wind Bomb Weaken Amplifier", false),
    WIND_BOMB_DURATION("Wind Bomb Duration", false),
    HUNTING_COMPANION_DURATION("Hunting Companion Duration", false),
    TACTICAL_MANEUVER_STUN_DURATION("Tactical Maneuver Stun Duration", false),
    SHARPSHOOTER_ARROW_SAVE_CHANCE("Sharpshooter Arrow Save Chance", false),
    WHIRLING_BLADE_KNOCKBACK("Whirling Blade Knockback", false),
    VOLLEY_COOLDOWN("Volley Cooldown", true),
    WHIRLING_BLADE_COOLDOWN("Whirling Blade Cooldown", true),
    WIND_BOMB_COOLDOWN("Wind Bomb Cooldown", true),
    HUNTING_COMPANION_COOLDOWN("Hunting Companion Cooldown", true),
    QUICKDRAW_COOLDOWN("Quickdraw Cooldown", true),
    PREDATOR_STRIKE_COOLDOWN("Predator Strike Cooldown", true),
    TACTICAL_MANEUVER_COOLDOWN("Tactical Maneuver Cooldown", true),
    CRYSTALLINE_COMBOS_RANGE("Crystalline Combos Range", false),
    CRYSTALLINE_COMBOS_DAMAGE("Crystalline Combos Damage", false),
    DESECRATING_SHOT_WEAKNESS_AMPLIFIER("Desecrating Shot Weakness Amplifier", false),
    DESECRATING_SHOT_RADIUS("Desecrating Shot Radius", false),
    DEVASTATION_DAMAGE("Devastation Damage", false),
    DEVASTATION_RADIUS("Devastation Radius", false),
    CHAIN_HEALING_WAVE_HEALING("Chain Healing Wave Healing", false),
    CHAIN_HEALING_WAVE_BOUNCE_RADIUS("Chain Healing Wave Bounce Radius", false),
    FLAME_TOTEM_DAMAGE("Flame Totem Damage", false),
    FLAME_TOTEM_EXPLOSION_RADIUS("Flame Totem Explosion Radius", false),
    FLAME_TOTEM_FIRE_DURATION("Flame Totem Fire Duration", false),
    TOTEMIC_PROJECTION_SPREAD("Totemic Projection Spread", false),
    CHAIN_LIGHTNING_DAMAGE("Chain Lightning Damage", false),
    CHAIN_LIGHTNING_BOUNCE_RADIUS("Chain Lightning Bounce Radius", false),
    DECAYED_TOTEM_SLOWNESS_AMPLIFIER("Decayed Totem Slowness Amplifier", false),
    DECAYED_TOTEM_RADIUS("Decayed Totem Radius", false),
    LIGHTNING_TOTEM_DAMAGE("Lightning Totem Damage", false),
    LIGHTNING_TOTEM_RADIUS("Lightning Totem Radius", false),
    EARTHEN_TREMOR_RADIUS("Earthen Tremor Radius", false),
    EARTHEN_TREMOR_KNOCKBACK("Earthen Tremor Knockback", false),
    CLEANSING_TOTEM_HEALING("Cleansing Totem Healing", false),
    CLEANSING_TOTEM_RADIUS("Cleansing Totem Radius", false),
    INTERCONNECTED_HAVOC_DAMAGE("Interconnected Havoc Damage", false),
    DESECRATING_SHOT_DAMAGE("Desecrating Shot Damage", false),
    SANCTUARY_SLOWNESS_AMPLIFIER("Sanctuary Slowness Amplifier", false),
    SANCTUARY_WEAKNESS_AMPLIFIER("Sanctuary Weakness Amplifier", false),
    SANCTUARY_VULNERABILITY_AMPLIFIER("Sanctuary Vulnerability Amplifier", false),
    DECAYED_TOTEM_DAMAGE("Decayed Totem Damage", false),
    EARTHEN_TREMOR_DAMAGE("Earthen Tremor Damage", false),
    TOTEMIC_PROJECTION_COOLDOWN("Totemic Projection Cooldown", true),
    WHIRLWIND_TOTEM_RADIUS("Whirlwind Totem Radius", false),
    FLAME_TOTEM_DURATION("Flame Totem Duration", false),
    LIGHTNING_TOTEM_DURATION("Lightning Totem Duration", false),
    CLEANSING_TOTEM_DURATION("Cleansing Totem Duration", false),
    WHIRLWIND_TOTEM_DURATION("Whirlwind Totem Duration", false),
    DECAYED_TOTEM_DURATION("Decayed Totem Duration", false),
    DESECRATING_SHOT_COOLDOWN("Desecrating Shot Cooldown", true),
    DEVASTATION_COOLDOWN("Devastation Cooldown", true),
    CHAIN_HEALING_WAVE_COOLDOWN("Chain Healing Wave Cooldown", true),
    FLAME_TOTEM_COOLDOWN("Flame Totem Cooldown", true),
    CHAIN_LIGHTNING_COOLDOWN("Chain Lightning Cooldown", true),
    DECAYED_TOTEM_COOLDOWN("Decayed Totem Cooldown", true),
    LIGHTNING_TOTEM_COOLDOWN("Lightning Totem Cooldown", true),
    EARTHEN_TREMOR_COOLDOWN("Earthen Tremor Cooldown", true),
    WHIRLWIND_TOTEM_COOLDOWN("Whirlwind Totem Cooldown", true),
    WHIRLWIND_TOTEM_SPEED_AMPLIFIER("Whirlwind Totem Speed Amplifier", false),
    CLEANSING_TOTEM_COOLDOWN("Cleansing Totem Cooldown", true),
    HAUNTING_SHADES_RADIUS("Haunting Shades Radius", false),
    HAUNTING_SHADES_DURATION("Haunting Shades Duration", false),
    GRASPING_CLAWS_DAMAGE("Grasping Claws Damage", false),
    GRASPING_CLAWS_RADIUS("Grasping Claws Radius", false),
    GRASPING_CLAWS_COOLDOWN("Grasping Claws Cooldown", true),
    VOODOO_BONDS_TRANSFER_TIME_LIMIT("Voodoo Bonds Transfer Time Limit", false),
    VOODOO_BONDS_RADIUS("Voodoo Bonds Radius", false),
    JUDGEMENT_CHAIN_DAMAGE("Judgement Chain Damage", false),
    JUDGEMENT_CHAIN_RANGE("Judgement Chain Range", false),
    CHOLERIC_FLAMES_DAMAGE("Choleric Flames Damage", false),
    CHOLERIC_FLAMES_RANGE("Choleric Flames Range", false),
    WITHERING_GAZE_DAMAGE("Withering Gaze Damage", false),
    WITHERING_GAZE_RANGE("Withering Gaze Range", false),
    RESTLESS_SOULS_DAMAGE("Restless Souls Damage", false),
    RESTLESS_SOULS_RADIUS("Restless Souls Radius", false),
    RESTLESS_SOULS_DURATION("Restless Souls Duration", false),
    SANGUINE_HARVEST_HEALING("Sanguine Harvest Healing", false),
    SANGUINE_HARVEST_RADIUS("Sanguine Harvest Radius", false),
    MELANCHOLIC_LAMENT_COOLDOWN("Melancholic Lament Cooldown", true),
    MELANCHOLIC_LAMENT_RADIUS("Melancholic Lament Radius", false),
    MELANCHOLIC_LAMENT_NEGATIVE_EFFECT_RECOVERY("Melancholic Lament Negative Effect Recovery", false),
    AMPLIFYING_HEX_DAMAGE("Amplifying Hex Damage", false),
    AMPLIFYING_HEX_RANGE("Amplifying Hex Range", false),
    CURSED_WOUND_DAMAGE_MODIFIER("Cursed Wound Damage Modifier", false),
    CURSED_WOUND_RADIUS("Cursed Wound Radius", false),
    GRASPING_CLAWS_PULL_STRENGTH("Grasping Claws Pull Strength", false),
    DARK_PACT_MELEE_DAMAGE("Dark Pact Melee Damage", false),
    DARK_PACT_REFRESH("Dark Pact Refresh", false),
    DARK_PACT_BUFF_DURATION("Dark Pact Buff Duration", false),
    DARK_PACT_ABSORPTION_HEALTH_CAP("Dark Pact Absorption Health Cap", false),
    VOODOO_BONDS_DAMAGE("Voodoo Bonds Damage", false),
    AMPLIFYING_HEX_DAMAGE_PER_EFFECT_POTENCY("Amplifying Hex Damage per Effect Potency", false),
    PHLEGMATIC_RESOLVE_RESISTANCE("Phlegmatic Resolve Resistance", false),
    PHLEGMATIC_RESOLVE_KNOCKBACK_RESISTANCE("Phlegmatic Resolve Knockback Resistance", false),
    SOUL_REND_HEALING("Soul Rend Healing", false),
    SOUL_REND_HEAL_CAP("Soul Rend Heal Cap", false),
    JUDGEMENT_CHAIN_BUFF_DURATION("Judgement Chain Buff Duration", false),
    MELANCHOLIC_LAMENT_WEAKNESS_AMPLIFIER("Melancholic Lament Weakness Amplifier", false),
    HAUNTING_SHADES_COOLDOWN("Haunting Shades Cooldown", true),
    GRASPING_CLAWS_SLOWNESS_AMPLIFIER("Grasping Claws Slowness Amplifier", false),
    GRASPING_CLAWS_SLOWNESS_DURATION("Grasping Claws Slowness Duration", false),
    WITHERING_GAZE_STUN_DURATION("Withering Gaze Stun Duration", false),
    WITHERING_GAZE_COOLDOWN("Withering Gaze Cooldown", true),
    WITHERING_GAZE_DOT_DURATION("Withering Gaze Dot Duration", false),
    SANGUINE_HARVEST_BLEED_AMPLIFIER("Sanguine Harvest Bleed Amplifier", false),
    SANGUINE_HARVEST_KNOCKBACK("Sanguine Harvest Knockback", false),
    CHOLERIC_FLAMES_DURATION("Choleric Flames Duration", false),
    CHOLERIC_FLAMES_KNOCKBACK("Choleric Flames Knockback", false),
    PHLEGMATIC_RESOLVE_ALLY_MODIFIER("Phlegmatic Resolve Ally Modifier", false),
    PHLEGMATIC_RESOLVE_RADIUS("Phlegmatic Resolve Radius", false),
    HAUNTING_SHADES_HEALING("Haunting Shades Healing", false),
    RESTLESS_SOULS_VEX_CAP("Restless Souls Vex Cap", false),
    CHOLERIC_FLAMES_COOLDOWN("Choleric Flames Cooldown", true),
    DARK_PACT_COOLDOWN("Dark Pact Cooldown", true),
    SOUL_REND_COOLDOWN("Soul Rend Cooldown", true),
    VOODOO_BONDS_COOLDOWN("Voodoo Bonds Cooldown", true),
    SANGUINE_HARVEST_COOLDOWN("Sanguine Harvest Cooldown", true),
    JUDGEMENT_CHAIN_COOLDOWN("Judgement Chain Cooldown", true),
    AMPLIFYING_HEX_COOLDOWN("Amplifying Hex Cooldown", true),
    COUNTER_STRIKE_DAMAGE("Counter Strike Damage", false),
    COUNTER_STRIKE_DAMAGE_REDUCTION("Counter Strike Damage Reduction", false),
    BRUTE_FORCE_DAMAGE("Brute Force Damage", false),
    BRUTE_FORCE_RADIUS("Brute Force Radius", false),
    SHIELD_BASH_DAMAGE("Shield Bash Damage", false),
    SHIELD_BASH_RANGE("Shield Bash Range", false),
    SHIELD_BASH_RADIUS("Shield Bash Radius", false),
    BODYGUARD_ABSORPTION_HEALTH("Bodyguard Absorption Health", false),
    BODYGUARD_RANGE("Bodyguard Range", false),
    BODYGUARD_STUN_RADIUS("Bodyguard Stun Radius", false),
    GLORIOUS_BATTLE_DAMAGE("Glorious Battle Damage", false),
    GLORIOUS_BATTLE_VELOCITY("Glorious Battle Velocity", false),
    COUNTER_STRIKE_DURATION("Counter Strike Duration", false),
    METEOR_SLAM_DAMAGE("Meteor Slam Damage", false),
    METEOR_SLAM_RADIUS("Meteor Slam Radius", false),
    GLORIOUS_BATTLE_RADIUS("Glorious Battle Radius", false),
    RAMPAGE_MAX_STACKS("Rampage Max Stacks", false),
    RAMPAGE_DAMAGE("Rampage Damage", false),
    RAMPAGE_DAMAGE_THRESHOLD("Rampage Damage Threshold", true),
    SHIELD_WALL_DAMAGE("Shield Wall Damage", false),
    SHIELD_WALL_KNOCKBACK("Shield Wall Knockback", false),
    SHIELD_WALL_DURATION("Shield Wall Duration", false),
    RIPOSTE_COOLDOWN("Riposte Cooldown", true),
    RIPOSTE_SWORD_BONUS_DAMAGE("Riposte Sword Bonus Damage", false),
    RAMPAGE_RESISTANCE_PER_STACK("Rampage Resistance Per Stack", false),
    CHALLENGE_MAX_ABSORPTION_HEALTH("Challenge Max Absorption Health", false),
    CHALLENGE_DAMAGE("Challenge Damage", false),
    CHALLENGE_ABSORPTION_HEALTH_PER_MOB("Challenge Absorption Health Per Mob", false),
    DEFENSIVE_LINE_RESISTANCE("Defensive Line Resistance", false),
    FRENZY_ATTACK_SPEED("Frenzy Attack Speed", false),
    SHIELD_BASH_DURATION("Shield Bash Duration", false),
    DEFENSIVE_LINE_DURATION("Defensive Line Duration", false),
    FRENZY_DURATION("Frenzy Duration", false),
    FRENZY_SPEED("Frenzy Speed", false),
    RIPOSTE_STUN_DURATION("Riposte Stun Duration", false),
    RAMPAGE_HEALING("Rampage Healing", false),
    CHALLENGE_COOLDOWN("Challenge Cooldown", true),
    SHIELD_BASH_COOLDOWN("Shield Bash Cooldown", true),
    DEFENSIVE_LINE_COOLDOWN("Defensive Line Cooldown", true),
    BODYGUARD_COOLDOWN("Bodyguard Cooldown", true),
    METEOR_SLAM_COOLDOWN("Meteor Slam Cooldown", true),
    SHIELD_WALL_COOLDOWN("Shield Wall Cooldown", true),
    ALCHEMICAL_ARTILLERY_SIZE("Alchemical Artillery Size", false),
    ALCHEMICAL_ARTILLERY_COOLDOWN("Alchemical Artillery Cooldown", true),
    UNSTABLE_AMALGAM_DROPPED_POTION_DAMAGE_MODIFIER("Unstable Amalgam Dropped Potion Damage Modifier", false),
    WARDING_REMEDY_ABSORPTION_DURATION("Warding Remedy Absorption Duration", false),
    WARDING_REMEDY_PULSES("Warding Remedy Pulses", false),
    ENERGIZING_ELIXIR_POTION_PRICE("Energizing Elixir Potion Price", false),
    ENERGIZING_ELIXIR_JUMP_BOOST_AMPLIFIER("Energizing Elixir Jump Boost Amplifier", false),
    SCORCHED_EARTH_CHARGE("Scorched Earth Charge", false),
    ESOTERIC_ENHANCEMENTS_CREEPER("Esoteric Enhancements Creeper", false),
    ALCHEMIST_POTION_RADIUS("Alchemist Potion Radius", false),
    IRON_TINCTURE_DURATION("Iron Tincture Duration", false),
    PANACEA_MOVEMENT_DURATION("Panacea Movement Duration", false),
    PANACEA_MOVEMENT_SPEED("Panacea Movement Speed", false),
    TABOO_POTION_RECHARGE_RATE("Taboo Potion Recharge Rate", false),
    SAPPER_HEAL("Sapper Heal", false),
    SNIPER_DAMAGE("Sniper Damage", false),
    HEX_EATER_DAMAGE("Hex Eater Damage", false),
    INFERNO_DAMAGE("Inferno Damage", false),
    JUNGLES_NOURISHMENT_RESISTANCE("Jungle's Nourishment Resistance", false),
    JUNGLES_NOURISHMENT_DURATION("Jungle's Nourishment Duration", false),
    JUNGLES_NOURISHMENT_HEALTH("Jungle's Nourishment Health", false),
    LIFE_DRAIN_HEAL("Life Drain Heal", false),
    DECAY_DAMAGE("Decay Damage", false),
    JUNGLES_NOURISHMENT_COOLDOWN("Jungle's Nourishment Cooldown", true),
    RAGE_OF_THE_KETER_COOLDOWN("Rage of the Keter Cooldown", true),
    QUAKE_RADIUS("Quake Radius", false),
    ERUPTION_RADIUS("Eruption Radius", false),
    REGENERATION_HEALING("Regeneration Healing", false),
    FIRST_STRIKE_DAMAGE("First Strike Damage", false),
    ADRENALINE_SPEED("Adrenaline Speed", false),
    REGICIDE_DAMAGE("Regicide Damage", false),
    RAGE_OF_THE_KETER_DAMAGE("Rage of the Keter Damage", false),
    RAGE_OF_THE_KETER_SPEED("Rage of the Keter Speed", false),
    SMITE_DAMAGE("Smite Damage", false),
    SLAYER_DAMAGE("Slayer Damage", false),
    DUELIST_DAMAGE("Duelist Damage", false),
    RAGE_OF_THE_KETER_DURATION("Rage of the Keter Duration", false),
    RECOIL_VELOCITY("Recoil Velocity", false),
    THUNDER_ASPECT_STUN_CHANCE("Thunder Aspect Stun Chance", false),
    QUAKE_DAMAGE("Quake Damage", false),
    DECAY_DURATION("Decay Duration", false),
    THURIBLE_PROCESSION_SPEED_AMPLIFIER("Thurible Procession Speed Amplifier", false),
    THURIBLE_PROCESSION_ATTACK_SPEED_AMPLIFIER("Thurible Procession Attack Speed Amplifier", false),
    HEAVENLY_BOON_RADIUS("Heavenly Boon Radius", false),
    HOLY_JAVELIN_SIZE("Holy Javelin Size", false),
    HALLOWED_BEAM_CHARGE("Hallowed Beam Charge", false),
    LUMINOUS_INFUSION_INFUSED_HITS("Luminous Infusion Infused Hits", false),
    REJUVENATION_HEALTH_THRESHOLD("Rejuvenation Health Threshold", false),
    HALLOWED_BEAM_RESISTANCE("Hallowed Beam Resistance", false),
    HALLOWED_BEAM_RESISTANCE_DURATION("Hallowed Beam Resistance Duration", false),
    ILLUMINATE_STRENGTH_AMPLIFIER("Illuminate Strength Amplifier", false),
    ILLUMINATE_ENHANCEMENT_RADIUS("Illuminate Enhancement Radius", false),
    CRUSADE_ENHANCEMENT_DAMAGE_AMPLIFIER("Crusade Enhancement Damage Amplifier", false),
    ASTRAL_OMEN_RANGE("Astral Omen Range", false),
    ASTRAL_OMEN_PULL_SPEED("Astral Omen Pull Speed", false),
    STARFALL_RADIUS("Starfall Radius", false),
    SAGES_INSIGHT_ABILITY_COUNT("Sage's Insight Ability Count", false),
    MAGMA_SHIELD_CONE("Magma Shield Cone", false),
    COSMIC_MOONBLADE_SLASHES("Cosmic Moonblade Slashes", false),
    ERUPTION_DAMAGE("Eruption Damage", false),
    PRISMATIC_SHIELD_ABSORPTION_DURATION("Prismatic Shield Absorption Duration", false),
    MANA_LANCE_CHARGE("Mana Lance Charge", false),
    PRISMATIC_SHIELD_ENHANCEMENT_DURATION("Prismatic Shield Enhancement Duration", false),
    PRISMATIC_SHIELD_ENHANCEMENT_DAMAGE("Prismatic Shield Enhancement Damage", false),
    PRISMATIC_SHIELD_ENHANCEMENT_HEALING("Prismatic Shield Enhancement Healing", false),
    FROST_NOVA_FROZEN_DURATION("Frost Nova Frozen Duration", false),
    BLIZZARD_DURATION("Blizzard Duration", false),
    DEADLY_RONDE_ANGLE("Deadly Ronde Angle", false),
    WIND_WALK_COOLDOWN_REDUCTION("Wind Walk Cooldown Reduction", false),
    SMOKESCREEN_WEAKNESS_AMPLIFIER("Smokescreen Weakness Amplifier", false),
    SMOKESCREEN_RANGE("Smokescreen Range", false),
    CLOAK_AND_DAGGER_STACKS_PER_KILL("Cloak and Dagger Stacks Per Kill", false),
    CLOAK_AND_DAGGER_STEALTH_DURATION("Cloak and Dagger Stealth Duration", false),
    BLADE_DANCE_RESISTANCE_DURATION("Blade Dance Resistance Duration", false),
    VICIOUS_COMBOS_RADIUS("Vicious Combos Radius", false),
    VICIOUS_COMBOS_VULNERABILITY_AMPLIFIER("Vicious Combos Vulnerability Amplifier", false),
    VICIOUS_COMBOS_ENHANCEMENT_DAMAGE_AMPLIFIER("Vicious Combos Enhancement Damage Amplifier", false),
    WIND_WALK_CHARGE("Wind Walk Charge", false),
    BODKIN_BLITZ_CHARGE("Bodkin Blitz Charge", false),
    COUP_DE_GRACE_ELITE_THRESHOLD("Coup de Grace Elite Threshold", false),
    BY_MY_BLADE_HASTE_DURATION("By My Blade Haste Duration", false),
    DAGGER_THROW_DAGGERS("Dagger Throw Daggers", false),
    WHIRLING_BLADE_CHARGES("Whirling Blade Charges", false),
    PREDATOR_STRIKE_ENEMIES_PIERCED("Predator Strike Enemies Pierced", false),
    SWIFTNESS_DODGE_CHANCE("Swiftness Dodge Chance", false),
    HUNTING_COMPANION_FOXES("Hunting Companion Foxes", false),
    SPLIT_ARROW_BOUNCES("Split Arrow Bounces", false),
    SPLIT_ARROW_RANGE("Split Arrow Range", false),
    HUNTING_COMPANION_STUN_DURATION("Hunting Companion Stun Duration", false),
    HUNTING_COMPANION_BLEED_DURATION("Hunting Companion Bleed Duration", false),
    HUNTING_COMPANION_HEALING("Hunting Companion Healing", false),
    WIND_BOMB_VORTEX_DURATION("Wind Bomb Vortex Duration", false),
    WIND_BOMB_VORTEX_PULL("Wind Bomb Vortex Pull", false),
    WIND_BOMB_VORTEX_RADIUS("Wind Bomb Vortex Radius", false),
    SWIFT_CUTS_EFFECT_DURATION("Swift Cuts Effect Duration", false),
    QUICKDRAW_PIERCING("Quickdraw Piercing", false),
    AGILITY_HASTE_AMPLIFIER("Agility Haste Amplifier", false),
    VOLLEY_PIERCING("Volley Piercing", false),
    HUNTING_COMPANION_EAGLES("Hunting Companion Eagles", false),
    TACTICAL_MANEUVER_CHARGE("Tactical Maneuver Charge", false),
    CHAIN_LIGHTNING_TARGETS("Chain Lightning Targets", false),
    DECAYED_TOTEM_TARGETS("Decayed Totem Targets", false),
    CRYSTALLINE_COMBOS_STACK_THRESHOLD("Crystalline Combos Stack Threshold", true),
    CRYSTALLINE_COMBOS_SHOT_COUNT("Crystalline Combos Shot Count", false),
    LIGHTNING_TOTEM_LIGHTNING_STORM_DURATION("Lightning Totem Lightning Storm Duration", false),
    INTERCONNECTED_HAVOC_STUN_DURATION("Interconnected Havoc Stun Duration", false),
    CRYSTALLINE_COMBOS_SHOT_DELAY("Crystalline Combos Shot Delay", true),
    INTERCONNECTED_HAVOC_RANGE("Interconnected Havoc Range", false),
    CHAIN_LIGHTNING_KNOCKBACK("Chain Lightning Knockback", false),
    CHAIN_LIGHTNING_CHARGES("Chain Lightning Charges", false),
    TOTEMIC_PROJECTION_SLOWNESS_AMPLIFIER("Totemic Projection Slowness Amplifier", false),
    TOTEMIC_PROJECTION_ENHANCEMENT_DAMAGE("Totemic Projection Enhancement Damage", false),
    TOTEMIC_PROJECTION_ENHANCEMENT_DAMAGE_DURATION("Totemic Projection Enhancement Damage Duration", false),
    LIGHTNING_TOTEM_PULSE_DELAY("Lightning Totem Pulse Delay", true),
    MELANCHOLIC_LAMENT_ENHANCEMENT_DAMAGE_MODIFIER("Melancholic Lament Enhancement Damage Modifier", false),
    MELANCHOLIC_LAMENT_ENHANCEMENT_DURATION("Melancholic Lament Enhancement Duration", false),
    SOUL_REND_ALLY_HEAL("Soul Rend Ally Heal", false),
    SOUL_REND_RADIUS("Soul Rend Radius", false),
    VOODOO_BONDS_RECEIVED_DAMAGE("Voodoo Bonds Received Damage", true),
    RESTLESS_SOULS_DEBUFF_RADIUS("Restless Souls Debuff Radius", false),
    RESTLESS_SOULS_DEBUFF_DURATION("Restless Souls Debuff Duration", false),
    VOODOO_BONDS_TRANSFER_DAMAGE("Voodoo Bonds Transfer Damage", false),
    DARK_PACT_ABSORPTION_HEALTH_PER_KILL("Dark Pact Absorption Health Per Kill", false),
    GRASPING_CLAWS_PROJECTILE_SPEED("Grasping Claws Projectile Speed", false),
    HAUNTING_SHADES_VULNERABILITY_MODIFIER("Haunting Shades Vulnerability Modifier", false),
    HAUNTING_SHADES_DAMAGE_MODIFIER("Haunting Shades Damage Modifier", false),
    AMPLIFYING_HEX_CONE("Amplifying Hex Cone", false),
    AMPLIFYING_HEX_ENHANCEMENT_HEALTH_THRESHOLD("Amplifying Hex Enhancement Health Threshold", true),
    AMPLIFYING_HEX_ENHANCEMENT_DAMAGE_BONUS("Amplifying Hex Enhancement Damage Bonus", false),
    CHOLERIC_FLAMES_ENHANCEMENT_RADIUS("Choleric Flames Enhancement Radius", false),
    CULLING_RESISTANCE_AMPLIFIER("Culling Resistance Amplifier", false),
    CULLING_DURATION("Culling Duration", false),
    SHIELD_WALL_ANGLE("Shield Wall Angle", false),
    RIPOSTE_DAMAGE("Riposte Damage", false),
    RIPOSTE_ROOT_DURATION("Riposte Root Duration", false),
    GLORIOUS_BATTLE_CHARGES("Glorious Battle Charges", false),
    SHIELD_BASH_PARRY_DURATION("Shield Bash Parry Duration", false),
    SHIELD_BASH_COOLDOWN_REDUCTION("Shield Bash Cooldown Reduction", false),
    RIPOSTE_SWORD_BONUS_DAMAGE_DURATION("Riposte Sword Bonus Damage Duration", false),
    TOUGHNESS_HEALTH("Toughness Health", false),
    TOUGHNESS_HEALING_INCREASE("Toughness Healing Increase", false),
    METEOR_SLAM_FALL_REQUIREMENT("Meteor Slam Fall Requirement", true),
    FRENZY_BONUS_DAMAGE("Frenzy Bonus Damage", false),
    BRUTE_FORCE_WAVES("Brute Force Waves", false),
    BRUTE_FORCE_WAVE_DELAY("Brute Force Wave Delay", true),
    METEOR_SLAM_REDUCED_THRESHOLD("Meteor Slam Reduced Threshold", false),
    METEOR_SLAM_JUMP_BOOST("Meteor Slam Jump Boost", false),
    METEOR_SLAM_DURATION("Meteor Slam Duration", false),
    CHALLENGE_MAX_MOBS("Challenge Max Mobs", false),
    CHALLENGE_COOLDOWN_REDUCTION_PER_MOB("Challenge Cooldown Reduction Per Mob", false),
    CHALLENGE_SPEED_PER_MOB("Challenge Speed Per Mob", false),
    DEFENSIVE_LINE_RANGE("Defensive Line Range", false),
    CHALLENGE_RANGE("Challenge Range", false),
    DEFENSIVE_LINE_DAMAGE_NEGATION("Defensive Line Damage Negation", false),
    DEFENSIVE_LINE_KNOCKBACK("Defensive Line Knockback", false),
    SHIELD_WALL_RADIUS("Shield Wall Radius", false),
    REVERB_DAMAGE("Reverb Damage", false);

    private final String displayName;
    private final boolean isNegative;

    MonumentaCharmAttributes(String displayName, boolean isNegative) {
        this.displayName = displayName;
        this.isNegative = isNegative;
    }

    public static MonumentaCharmAttributes fromJson(JsonElement e) {
        return valueOf(e.getAsString().toUpperCase());
    }

    public boolean isNegative() {
        return isNegative;
    }

    public String displayName() {
        return displayName;
    }

    public enum Operation {
        ADD, MULTIPLY;

        public static Operation fromJson(JsonElement e) {
            return valueOf(e.getAsString().toUpperCase());
        }
    }
}