metadata.format.version = "1.1"

[versions]
fabric-loader = "0.16.10"
mixinextras = "0.5.0-beta.5"

paper-api = "1.20.4-R0.1-SNAPSHOT"
nbtapi = "2.12.4"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
mixinextras = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras" }

paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
nbtapi-plugin = { module = "de.tr7zw:item-nbt-api-plugin", version.ref = "nbtapi" }
