metadata.format.version = "1.1"

[versions]
fabricloader = "1.0.2"
mixin-extras = "0.4.0"
tinyremapper = "0.10.3"

paper-api = "1.20.4-R0.1-SNAPSHOT"
nbtapi = "2.12.4"
semver = "5.3.0"

gradle-spotless = "6.25.0"
gradle-paperweight = "1.1.2"
gradle-shadow = "8.1.1"

[libraries]
fabricloader = { module = "com.floweytf.fabricpaperloader:fabric-paper-loader", version.ref = "fabricloader" }
mixin-extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }
tinyremapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tinyremapper" }

paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }
nbtapi-plugin = { module = "de.tr7zw:item-nbt-api-plugin", version.ref = "nbtapi" }
semver = { module = "org.semver4j:semver4j", version.ref = "semver" }

gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "gradle-spotless" }
gradle-paperweight = { module = "com.playmonumenta.paperweight-aw:paperweight-userdev", version.ref = "gradle-paperweight" }
gradle-shadow = { module = "com.github.johnrengelman:shadow", version.ref = "gradle-shadow" }
